INSERT INTO exercises (title,
                       difficulty,
                       task,
                       number_of_vars,
                       number_of_constraints,
                       target_vars,
                       constraint_vars,
                       constraint_vals)
VALUES ('Ex 1',
        'EASY',
        'Exercise description...',
        2,
        2,
        'target vars...',
        'constraint vars...',
        'constraint vals...'),
       ('Ex 2',
        'MEDIUM',
        'Exercise description...',
        2,
        2,
        'target vars...',
        'constraint vars...',
        'constraint vals...'),
       ('Ex 3',
        'HARD',
        'Exercise description...',
        2,
        2,
        'target vars...',
        'constraint vars...',
        'constraint vals...')
